spring:
  application:
    name: task-service-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/taskdb}
    username: ${SPRING_DATASOURCE_USERNAME:taskuser}
    password: ${SPRING_DATASOURCE_PASSWORD:taskpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

app:
  jwt:
    secret: "change-this-secret-to-a-strong-long-value-32bytes-minimum"
    expiration-ms: 3600000
